# parent image
FROM tensorflow/tensorflow:nightly-gpu-py3

# set working directory
WORKDIR /development

# Copy the current directory contents into the destination directory
ADD . /development

# setup from commandline
# RUN apt-get update && apt-get install -y \
#     python-opencv \
#     && \
# apt-get clean && \
# apt-get autoremove && \
# rm -rf /var/lib/apt/list/*

# install requirements.txt
RUN pip install --trusted-host pypi.python.org -r requirements.txt
